name: learn-github-actions
run-name: ${{ github.actor }} is testing setup scripts
on: [push]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install -y --no-install-recommends vim zsh tmux
      - run: bash setup.sh
      - run: bash setup.sh
